### ISSUE TITLE
Add information about funding to README.md

### ISSUE THREAD

**Issue by pbiecek** [ModelOriented/auditor#126]
Was it MLGenSig?

**Comment by agosiewska** [comment]
Information about funding is in section 'More'

> Acknowledgments: Work on this package was financially supported by the ‘NCN Opus grant 2016/21/B/ST6/02176’.

**Comment by pbiecek** [comment]
Right, thanks
Maybe we can move it to the end of the readme to be consistent with ibreakdown and ingredients?

**Comment by agosiewska** [comment]
Sure, done :)

**Comment by pbiecek** [comment]
thanks
