### ISSUE TITLE
Dragons Example Fails

### ISSUE THREAD

**Issue by ZellW** [ModelOriented/auditor#127]
Following the **auditor** example featuring the **dragons** dataset:  

`lm_model <- lm(life_length ~ ., data = dragons)`
`lm_exp <- explain(lm_model, label = "lm", data = dragons, y = dragons$life_length)`
`lm_mr <- model_residual(lm_exp)`

Results in an error:

Error in `$<-.data.frame`(`*tmp*`, "_y_", value = c(1368.43310539739, : replacement has 2000 rows, data has 0

Same issue using the **dragons** data from DALEX or DALEX2.

**Comment by agosiewska** [comment]
I cannot replicate this error, could you, please, send session info?

**Comment by agosiewska** [comment]
I am guessing that you have an older version of DALEX

**Comment by ZellW** [comment]
You were right.  I had DALEX 0.4.4.  The problem I experienced does not exist with 0.4.7.

I am embarrassed - I should have caught this!
