### ISSUE TITLE
`score_*` functions with optional `data` argument

### ISSUE THREAD

**Issue by pbiecek** [ModelOriented/auditor#130]
I found `score_*` functions very useful. Thanks for them!

Would you consider adding an additional argument `data`? If specified then model performance may be calculated on a specific dataset (like outof-time / out-of sample datasets).

**Comment by pbiecek** [comment]
And it would be great to have the same feature for `model_performance()`

**Comment by hbaniecki** [comment]
#132

**Comment by hbaniecki** [comment]
Hopefully this one is covered

**Comment by pbiecek** [comment]
thanks
