### ISSUE TITLE
put the threshold for yhat as an optional argument

### ISSUE THREAD

**Issue by pbiecek** [ModelOriented/auditor#131]
Functions `auditor::score_f1()` and `auditor:::confusionmatrix()` use the 0.5 thresholding for model prediction `yhat`. 
It would be useful to have this threshold as an optional argument in these functions (and likely some other score_* functions).

Possible names for this argument `threshold` or `cutoff`

**Comment by pbiecek** [comment]
@hbaniecki thanks, `cutoff` is working for `score_f1` but is not on the list of arguments for `model_performance`

**Comment by hbaniecki** [comment]
Right. There is a need for `...` parameter in `model_performance`

**Comment by pbiecek** [comment]
thanks

**Comment by hbaniecki** [comment]
This looks like done.
