### ISSUE TITLE
obsolete example for `plot_prediction`

### ISSUE THREAD

**Issue by pbiecek** [ModelOriented/auditor#136]
It looks like the line 
```
plot(mr_lm, type = "prediction", abline = TRUE)
```
in the example for plot_prediction (see  https://modeloriented.github.io/auditor/reference/plot_prediction.html) is obsolete, since the `type = "prediction"` does nothing.

it would be better to remove this line from examples

**Comment by hbaniecki** [comment]
What do you mean by "does nothing" ? 
```

**Comment by pbiecek** [comment]
Plots in the example are the same, (this is why I was surprised) 
but now I see that this example is suppose to show that `plot(type = "prediction")` can be used instead of `plot_prediction()`

So maybe it is enough to add a comment that these two commands are equivalent.
