### ISSUE TITLE
Splitting rows in legend in D3 plots

### ISSUE THREAD

**Issue by agosiewska** [ModelOriented/auditor#139]
It would be great to be able to split legend into multiple lines
I have generated a lift chart for 20 models, and cannot use the legend to turn most of them off :( as they are invisible in the legend
![image](https://user-images.githubusercontent.com/18423383/67053748-27fd2280-f0f7-11e9-8cee-19d2a238fb79.png)

@hbaniecki  😁

**Comment by hbaniecki** [comment]
Sure, i will take care of it

**Comment by hbaniecki** [comment]
By the way, `ggplot2` plots legends do not work either.
![temp](https://user-images.githubusercontent.com/32574004/67146669-a55a9b80-f28d-11e9-93f2-c05cd25aa8c9.png)

**Comment by agosiewska** [comment]
Thank you @hbaniecki 
yes, I knew about ggplot, yet for more than 3 models are hard to distinguish anyway due to colors.

**Comment by agosiewska** [comment]
Btw, I have experienced a bug in legend.
Including special characters in labels, for example `(` makes legend not work.

```
library(auditor)

titanic <- na.omit(DALEX::titanic)
titanic$survived <- titanic$survived == "yes"

# fit a model
model_glm <- glm(survived ~ ., family = binomial, data = titanic)

# use DALEX package to wrap up a model into explainer
exp_glm <- DALEX::explain(model_glm, data = titanic, y = titanic$survived, label = "glm(1)")

# validate a model with auditor
library(auditor)
eva_glm <- model_evaluation(exp_glm)

model_glm_2 <- glm(survived ~ .-age, family = binomial, data = titanic)
exp_glm_2 <- DALEX::explain(model_glm_2, data = titanic, y = titanic$survived, label = "glm(2)")
eva_glm_2 <- model_evaluation(exp_glm_2)

plotD3_lift(eva_glm, eva_glm_2)
```

**Comment by hbaniecki** [comment]
Yes. This legend works on css class names. I made `space` in label work though.
https://stackoverflow.com/questions/448981/which-characters-are-valid-in-css-class-names-selectors

**Comment by hbaniecki** [comment]
Maybe it could work if someone finds reliable "remove all special characters" regexp

**Comment by hbaniecki** [comment]
I guess that i can make it work regardless of label
