### ISSUE TITLE
Add score_auprc and AUPRC plot

### ISSUE THREAD

**Issue by hbaniecki** [ModelOriented/auditor#146]
- https://stats.stackexchange.com/questions/10501/calculating-aupr-in-r
- https://github.com/DominikRafacz/auprc

**Comment by hbaniecki** [comment]
maybe `score_prc` and `plot_prc` as it is `precision-recall curve`

**Comment by agosiewska** [comment]
Will do :)
I think score_auprc and plot_prc names would be best.
