### ISSUE TITLE
score_auc code

### ISSUE THREAD

**Issue by hbaniecki** [ModelOriented/auditor#154]
@agosiewska shouldn't it be `pred_sorted$y` as `pred_sorted` is `data.frame` ? Also, the `cutoff` is not used anywhere.
https://github.com/ModelOriented/auditor/blob/6f0388546406691728bbbcf4284ffbe76a9a8940/R/score_auc.R#L50-L57

**Comment by agosiewska** [comment]
Thanks, can you check my PR?
https://github.com/ModelOriented/auditor/pull/155
