### ISSUE TITLE
improve AUC/ROC calculation

### ISSUE THREAD

**Issue by hbaniecki** [ModelOriented/auditor#157]
Can't really share code and data, but apparently, it is possible for the `score_auc` function to return a value higher than 1.

![image](https://user-images.githubusercontent.com/32574004/125641098-17d66904-6097-4b39-9c81-5c96367fd722.png)

**Comment by agosiewska** [comment]
Can you share y and predicted y?

**Comment by hbaniecki** [comment]
![image](https://user-images.githubusercontent.com/32574004/126047245-736c2f82-2d3e-4717-9e92-a6082eea09eb.png)

[example.zip](https://github.com/ModelOriented/auditor/files/6835184/example.zip)

**Comment by hbaniecki** [comment]
@agosiewska this got fixed in https://github.com/ModelOriented/auditor/issues/154 (I am using CRAN version). Let's send v `1.3.1` to CRAN.

**Comment by pbiecek** [comment]
The way the auditor calculates AUC is unstable (depends on ordering of rows) when the model returns a small number of possible values. imho it is better to use the procedure recently implemented in DALEX

issue:
https://github.com/ModelOriented/DALEX/issues/442

implementation:
https://github.com/ModelOriented/DALEX/commit/4d533ea39c37bf581943fbf0e51fc4f5af2bfc6e#diff-bada66e51c0a14d28d58a1ffcb592ab1207c7ebf2a467f4ce2a9bf5e4b084b50

**Comment by hbaniecki** [comment]
I believe this got fixed. Maybe it is time to send `v1.3.4` to CRAN.
