### ISSUE TITLE
New theme_drwhy for D3 plots

### ISSUE THREAD

**Issue by agosiewska** [ModelOriented/auditor#53]
- [x] plotACF() 
- [x] plotAutocorrelation() 
- [x] plotCooksDistance() 
- [x] plotHalfNormal() 
- [x] plotLIFT() 
- [ ]  plotModelCorrelation()
- [ ]  plotModelPCA() 
- [ ] plotModelRanking() 
- [x]  plotPrediction() 
- [x]  plotREC() 
- [x] plotResidual() 
- [ ] plotResidualBoxplot() 
- [ ] plotResidualDensity() 
- [x]  plotROC() 
- [x] plotRROC() 
- [x] plotScaleLocation() 
- [ ] plotTwoSidedECDF()

**Comment by agosiewska** [comment]
plotD3Residual due to #54

**Comment by hbaniecki** [comment]
plotD3Prediction and plotD3Autocorrelation due to #66

**Comment by agosiewska** [comment]
Now we can track the missing plots in README :) (table at the end)
https://github.com/MI2DataLab/auditor/blob/master/README.md

**Comment by hbaniecki** [comment]
- [ ]  plotModelCorrelation() -  no interactivity here (?)
- [ ]  plotModelPCA() - can be done
- [ ] plotModelRanking() - possibly this concept http://bl.ocks.org/nbremer/21746a9668ffdf6d8242
- [ ] plotResidualBoxplot() - no interactivity here (?)
- [ ] plotResidualDensity() - todo for sure
- [ ] plotTwoSidedECDF() - todo for sure

**Comment by agosiewska** [comment]
Agree :)
The most important for me is the modelRadar plot.

**Comment by hbaniecki** [comment]
This project has been finished.
